[build]
  base = ""  # Root of your repo
  publish = "frontend"  # Adjust if your frontend folder is named differently
  command = "npm run build"  # Or your actual frontend build command

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200